sudo: false
language: node_js
node_js:
  - '6'
  - '8'
before_install:
  - 'wget http://www.eu.apache.org/dist/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz'
  - 'tar xf zookeeper-3.4.6.tar.gz'
  - 'mv zookeeper-3.4.6/conf/zoo_sample.cfg zookeeper-3.4.6/conf/zoo.cfg'
  - './zookeeper-3.4.6/bin/zkServer.sh start'
install:
  - npm i npminstall && npminstall
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov